[project]
name = "openblas_buildsys_snips"
version = "0.1.0"
description = "Snippets for working on the meson build for OpenBLAS"
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
jupyter = "1.0.0.*"
jupytext = "1.16.1.*"
pdm = "2.12.4.*"
pip = "24.0.*"
spin = ">=0.13,<0.14"
doit = ">=0.36.0,<0.37"
pydevtool = ">=0.3.0,<0.4"
rich-click = ">=1.8.8,<2"
pythran = ">=0.17.0,<0.18"
pybind11 = ">=2.13.6,<3"
ccache = ">=4.11.2,<5"
libgcc-ng = ">=14.2.0,<15"
pthread-stubs = ">=0.4,<0.5"
openblas = ">=0.3.29,<0.4"
cython = ">=3.0.12,<4"
compilers = ">=1.9.0,<2"
meson = ">=1.7.1,<2"
meson-python = ">=0.17.1,<0.18"
ninja = ">=1.12.1,<2"
numpy = ">=2.2.4,<3"
pkg-config = ">=0.29.2,<0.30"
pooch = ">=1.8.2,<2"
pytest = ">=8.3.5,<9"
pytest-cov = ">=6.1.1,<7"
pytest-xdist = ">=3.6.1,<4"
pytest-timeout = ">=2.3.1,<3"
asv = ">=0.6.4,<0.7"
conda-build = ">=25.3.2,<26"
hypothesis = ">=6.131.0,<7"

[pypi-dependencies]
openblas_buildsys_snips = { path = "./", editable = true}
