[project]
name = "openblas_buildsys_snips"
version = "0.1.0"
description = "Snippets for working on the meson build for OpenBLAS"
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
jupyter = "1.0.0.*"
jupytext = "1.16.1.*"
pdm = "2.12.4.*"
